import fs from 'node:fs'
import path from 'node:path'

const SETTINGS_CONTENT = `<!-- Auto-generated by ts-mcp --init. Do not edit manually. -->

# TypeScript Code Navigation (ts-mcp)

For TypeScript code navigation, ALWAYS prefer ts-mcp tools over Grep/Read:

- Symbol definition → \`goto_definition\` (not Grep)
- Symbol references → \`find_references\` (not Grep)
- Symbol search → \`workspace_symbols\` (not Grep)
- File structure → \`document_symbols\` (not Read)
- Type navigation → \`goto_type_definition\`
- Member listing → \`list_members\`
- Call chain → \`call_hierarchy\`
- Type implementations → \`type_hierarchy\`
- Change impact → \`impact_analysis\`
- Type/docs info → \`get_type_info\`
- Rename → \`rename_symbol\`
- Errors → \`diagnostics\`

## Custom TSDoc tags

\`get_type_info\` automatically extracts \`@ts-mcp-*\` tags from JSDoc.
Use these to embed agent-readable metadata directly in source code:

\`\`\`typescript
/**
 * @ts-mcp-context Requires authenticated session
 * @ts-mcp-related validateToken, refreshSession
 * @ts-mcp-risk Modifies user state — call impact_analysis before changing
 */
\`\`\`

Tags appear in the \`customTags\` field of \`get_type_info\` responses.
Define project-specific tags as needed (e.g., \`@ts-mcp-owner\`, \`@ts-mcp-layer\`).
`

const CLAUDE_MD_REFERENCE = 'See [ts-mcp-settings.md](ts-mcp-settings.md) for TypeScript code navigation tools.'
const SETTINGS_FILE = 'ts-mcp-settings.md'
const MCP_SERVER_KEY = 'ts-mcp'

export function initProject(workspace: string): void {
  const claudeDir = path.join(workspace, '.claude')

  if (!fs.existsSync(claudeDir)) {
    fs.mkdirSync(claudeDir, { recursive: true })
  }

  setupSettings(claudeDir)
  setupClaudeMd(claudeDir)
  setupMcpJson(workspace)
}

function setupSettings(claudeDir: string): void {
  const settingsPath = path.join(claudeDir, SETTINGS_FILE)
  fs.writeFileSync(settingsPath, SETTINGS_CONTENT)
  console.log('✓ .claude/ts-mcp-settings.md — written')
}

function setupClaudeMd(claudeDir: string): void {
  const claudeMdPath = path.join(claudeDir, 'CLAUDE.md')

  if (fs.existsSync(claudeMdPath)) {
    const existing = fs.readFileSync(claudeMdPath, 'utf-8')
    if (existing.includes(SETTINGS_FILE)) {
      console.log('✓ .claude/CLAUDE.md — reference already exists')
      return
    }
    fs.writeFileSync(claudeMdPath, existing.trimEnd() + '\n\n' + CLAUDE_MD_REFERENCE + '\n')
    console.log('✓ .claude/CLAUDE.md — appended reference')
  } else {
    fs.writeFileSync(claudeMdPath, CLAUDE_MD_REFERENCE + '\n')
    console.log('✓ .claude/CLAUDE.md — created')
  }
}

function setupMcpJson(workspace: string): void {
  const mcpJsonPath = path.join(workspace, '.mcp.json')

  const serverConfig = {
    command: 'ts-mcp',
    args: [workspace],
  }

  if (fs.existsSync(mcpJsonPath)) {
    const existing = JSON.parse(fs.readFileSync(mcpJsonPath, 'utf-8'))
    if (existing.mcpServers?.[MCP_SERVER_KEY]) {
      console.log('✓ .mcp.json — ts-mcp server already configured')
      return
    }
    existing.mcpServers = existing.mcpServers ?? {}
    existing.mcpServers[MCP_SERVER_KEY] = serverConfig
    fs.writeFileSync(mcpJsonPath, JSON.stringify(existing, null, 2) + '\n')
    console.log('✓ .mcp.json — appended ts-mcp server')
  } else {
    const config = { mcpServers: { [MCP_SERVER_KEY]: serverConfig } }
    fs.writeFileSync(mcpJsonPath, JSON.stringify(config, null, 2) + '\n')
    console.log('✓ .mcp.json — created')
  }
}
